import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    padding: 16,
    backgroundColor: "#F6F7FB",
  },
  card: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
    // iOS shadow
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    // Android shadow
    elevation: 3,
  },
  imageRow: { flexDirection: "row", gap: 14 },
  imageWrap: { position: "relative" },
  image: { width: 110, height: 110, borderRadius: 12, backgroundColor: "#EEE" },
  imagePlaceholder: { alignItems: "center", justifyContent: "center" },
  imagePlaceholderText: { color: "#9AA0A6" },
  ribbon: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: "#E74C3C",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  ribbonText: { color: "#fff", fontSize: 12, fontWeight: "600" },
  headerInfo: { flex: 1, justifyContent: "space-between" },
  title: { fontSize: 18, fontWeight: "700", color: "#111827" },
  badgeRow: { flexDirection: "row", gap: 8, marginTop: 8, flexWrap: "wrap" },
  badge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
  badgePrimary: { backgroundColor: "#EEF2FF" },
  badgeDanger: { backgroundColor: "#FEE2E2" },
  badgeMuted: { backgroundColor: "#F3F4F6" },
  badgeText: { color: "#1F2937", fontSize: 12, fontWeight: "600" },
  metaText: { color: "#6B7280", marginTop: 6 },
  noteBox: {
    marginTop: 12,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#EEF2F7",
    borderRadius: 12,
    padding: 12,
  },
  noteTitle: { fontWeight: "700", color: "#111827", marginBottom: 4 },
  noteText: { color: "#374151" },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 12,
  },
  optionWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  optionChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    gap: 6,
  },
  optionChipText: { color: "#111827", fontWeight: "600", maxWidth: 180 },
  optionMeta: { color: "#6B7280", fontSize: 12 },
  emptyOption: { color: "#6B7280" },
  divider: { height: 1, backgroundColor: "#EEF2F7", marginVertical: 12 },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  labelText: { color: "#6B7280" },
  valueText: { color: "#111827", fontWeight: "700" },
  emLabel: { fontSize: 16, color: "#374151" },
  emValue: { fontSize: 18, color: "#111827" },
  totalPill: {
    marginTop: 12,
    alignSelf: "flex-end",
    backgroundColor: "#111827",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
  },
  totalPillText: { color: "white", fontWeight: "700" },
  btn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  btnText: { fontWeight: "700" },
  btnPrimary: { backgroundColor: "#111827" },
  btnPrimaryText: { color: "#FFFFFF" },
  btnGhost: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  btnGhostText: { color: "#111827" },
  center: { alignItems: "center", justifyContent: "center" },
  emptyTitle: { fontSize: 16, fontWeight: "700", color: "#111827" },
  emptySub: { marginTop: 6, color: "#6B7280" },
});
